name = "BitPermutations"
uuid = "81206824-6155-40a8-95f7-18696067be4d"
authors = ["Giacomo Giudice <ggiac93@gmail.com>"]
version = "0.3.2"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[compat]
Combinatorics = "1"
SIMD = "3"
julia = "1.6"
