name = "BitPermutations"
uuid = "81206824-6155-40a8-95f7-18696067be4d"
authors = ["Giacomo Giudice <ggiac93@gmail.com>"]
version = "0.1.2"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[compat]
Combinatorics = "1"
julia = "1.5"
